-- 코드를 입력하세요
SELECT A.AUTHOR_ID AS AUTHOR_ID, A.AUTHOR_NAME AS AUTHOR_NAME, B.CATEGORY AS CATEGORY, 
SUM(BS.SALES * B.PRICE)  AS TOTAL_SALES

FROM BOOK B 
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID

WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY  AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID , CATEGORY DESC;