
SELECT YEAR(e1.DIFFERENTIATION_DATE) AS YEAR, 
e2.MAXSIZE - e1.SIZE_OF_COLONY AS YEAR_DEV, 
e1.ID AS ID
FROM ECOLI_DATA e1
JOIN
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
 , MAX(SIZE_OF_COLONY) AS MAXSIZE
FROM ECOLI_DATA 
GROUP BY YEAR)  
e2
ON YEAR(e1.DIFFERENTIATION_DATE) = e2.YEAR 
ORDER BY YEAR, YEAR_DEV

